app: rick-and-morty

deployment:
  image:
    registry: yuvals41
    repository: rick-and-morty
    tag: latest
    pullPolicy: Always
  rollingUpdate:
    maxUnavailable: 50%
    maxSurge: 50%
  ports:
    app: 8080
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      #cpu: "1500m"
  command: "python3"
  args: "app.py"
  healthProbes: 
    enabled: true
    readinessProbe:
      enabled: true
      path: /healthcheck
      port: 8080
    livenessProbe:
      enabled: true
      path: /healthcheck
      port: 8080
  securityContext:
    runAsNonRoot: true
    runAsUser: 1500
    runAsGroup: 1500
  podAnnotations: {}

service:
  type: ClusterIP
  protocol: TCP
  port: 80

ingress:
  enabled: true
  hostname: localhost
  path: /