apiVersion: v1
kind: Service
metadata:
  name: rick-and-morty
  labels:
    app: rick-and-morty
spec:
  type: ClusterIP
  selector:
    app: rick-and-morty
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP